language: node_js
sudo: false
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
before_script:
  - mongo uptime-test --eval 'db.addUser("uptime2-test", "test");'
services: mongodb
matrix:
    fast_finish: true
    allow_failures:
     - node_js: "0.11"
     - node_js: "0.12"
     - node_js: "4.0"
     - node_js: "4.1"
script:
  - 'make'
notifications:
  email: false
